const PRICING = [
  {
    bq_region: "asia-east1",
    bq_region_name: "Taiwan (asia-east1)",
    active_logical_storage: "0.02",
    long_term_logical_storage: "0.01",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.046",
    bq_enterprise_edition: "0.069",
    bq_enterprise_1_year: "0.0552",
    bq_enterprise_3_years: "0.0414",
    bq_enterprise_plus_edition: "0.115",
    bq_enterprise_plus_1_year: "0.092",
    bq_enterprise_plus_3_years: "0.069",
    bq_flat_rate_flex: "0.046",
    bq_flat_rate_monthly: "23",
    bq_flat_rate_annual: "19.55",
    bq_on_demand: "5.75",
  },
  {
    bq_region: "asia-east2",
    bq_region_name: "Hong Kong (asia-east2)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.056",
    bq_enterprise_edition: "0.084",
    bq_enterprise_1_year: "0.0672",
    bq_enterprise_3_years: "0.0504",
    bq_enterprise_plus_edition: "0.14",
    bq_enterprise_plus_1_year: "0.112",
    bq_enterprise_plus_3_years: "0.084",
    bq_flat_rate_flex: "0.056",
    bq_flat_rate_monthly: "28",
    bq_flat_rate_annual: "23.8",
    bq_on_demand: "7",
  },
  {
    bq_region: "asia-northeast1",
    bq_region_name: "Tokyo (asia-northeast1)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.051",
    bq_enterprise_edition: "0.0765",
    bq_enterprise_1_year: "0.0612",
    bq_enterprise_3_years: "0.0459",
    bq_enterprise_plus_edition: "0.1275",
    bq_enterprise_plus_1_year: "0.102",
    bq_enterprise_plus_3_years: "0.0765",
    bq_flat_rate_flex: "0.048",
    bq_flat_rate_monthly: "24",
    bq_flat_rate_annual: "20.4",
    bq_on_demand: "6",
  },
  {
    bq_region: "asia-northeast2",
    bq_region_name: "Osaka (asia-northeast2)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.051",
    bq_enterprise_edition: "0.0765",
    bq_enterprise_1_year: "0.0612",
    bq_enterprise_3_years: "0.0459",
    bq_enterprise_plus_edition: "0.1275",
    bq_enterprise_plus_1_year: "0.102",
    bq_enterprise_plus_3_years: "0.0765",
    bq_flat_rate_flex: "0.048",
    bq_flat_rate_monthly: "24",
    bq_flat_rate_annual: "20.4",
    bq_on_demand: "6",
  },
  {
    bq_region: "asia-northeast3",
    bq_region_name: "Seoul (asia-northeast3)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.051",
    bq_enterprise_edition: "0.0765",
    bq_enterprise_1_year: "0.0612",
    bq_enterprise_3_years: "0.0459",
    bq_enterprise_plus_edition: "0.1275",
    bq_enterprise_plus_1_year: "0.102",
    bq_enterprise_plus_3_years: "0.0765",
    bq_flat_rate_flex: "0.048",
    bq_flat_rate_monthly: "24",
    bq_flat_rate_annual: "20.4",
    bq_on_demand: "6",
  },
  {
    bq_region: "asia-south1",
    bq_region_name: "Mumbai (asia-south1)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.046",
    bq_enterprise_edition: "0.069",
    bq_enterprise_1_year: "0.0552",
    bq_enterprise_3_years: "0.0414",
    bq_enterprise_plus_edition: "0.115",
    bq_enterprise_plus_1_year: "0.092",
    bq_enterprise_plus_3_years: "0.069",
    bq_flat_rate_flex: "0.048",
    bq_flat_rate_monthly: "24",
    bq_flat_rate_annual: "20.4",
    bq_on_demand: "6",
  },
  {
    bq_region: "asia-south2",
    bq_region_name: "Delhi (asia-south2)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.046",
    bq_enterprise_edition: "0.069",
    bq_enterprise_1_year: "0.0552",
    bq_enterprise_3_years: "0.0414",
    bq_enterprise_plus_edition: "0.115",
    bq_enterprise_plus_1_year: "0.092",
    bq_enterprise_plus_3_years: "0.069",
    bq_flat_rate_flex: "0.048",
    bq_flat_rate_monthly: "24",
    bq_flat_rate_annual: "20.4",
    bq_on_demand: "6",
  },
  {
    bq_region: "asia-southeast1",
    bq_region_name: "Singapore (asia-southeast1)",
    active_logical_storage: "0.02",
    long_term_logical_storage: "0.01",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.049",
    bq_enterprise_edition: "0.0735",
    bq_enterprise_1_year: "0.0588",
    bq_enterprise_3_years: "0.0441",
    bq_enterprise_plus_edition: "0.1225",
    bq_enterprise_plus_1_year: "0.098",
    bq_enterprise_plus_3_years: "0.0735",
    bq_flat_rate_flex: "0.054",
    bq_flat_rate_monthly: "27",
    bq_flat_rate_annual: "22.95",
    bq_on_demand: "6.75",
  },
  {
    bq_region: "asia-southeast2",
    bq_region_name: "Jakarta (asia-southeast2)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.044",
    bq_enterprise_edition: "0.066",
    bq_enterprise_1_year: "0.0528",
    bq_enterprise_3_years: "0.0396",
    bq_enterprise_plus_edition: "0.11",
    bq_enterprise_plus_1_year: "0.088",
    bq_enterprise_plus_3_years: "0.066",
    bq_flat_rate_flex: "0.048",
    bq_flat_rate_monthly: "24",
    bq_flat_rate_annual: "20.4",
    bq_on_demand: "6",
  },
  {
    bq_region: "australia-southeast1",
    bq_region_name: "Sydney (australia-southeast1)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.054",
    bq_enterprise_edition: "0.081",
    bq_enterprise_1_year: "0.0648",
    bq_enterprise_3_years: "0.0486",
    bq_enterprise_plus_edition: "0.135",
    bq_enterprise_plus_1_year: "0.108",
    bq_enterprise_plus_3_years: "0.081",
    bq_flat_rate_flex: "0.052",
    bq_flat_rate_monthly: "26",
    bq_flat_rate_annual: "22.1",
    bq_on_demand: "6.5",
  },
  {
    bq_region: "australia-southeast2",
    bq_region_name: "Melbourne (australia-southeast2)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.054",
    bq_enterprise_edition: "0.081",
    bq_enterprise_1_year: "0.0648",
    bq_enterprise_3_years: "0.0486",
    bq_enterprise_plus_edition: "0.135",
    bq_enterprise_plus_1_year: "0.108",
    bq_enterprise_plus_3_years: "0.081",
    bq_flat_rate_flex: "0.052",
    bq_flat_rate_monthly: "26",
    bq_flat_rate_annual: "22.1",
    bq_on_demand: "6.5",
  },
  {
    bq_region: "eu",
    bq_region_name: "Europe (multi-region)",
    active_logical_storage: "0.02",
    long_term_logical_storage: "0.01",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.044",
    bq_enterprise_edition: "0.066",
    bq_enterprise_1_year: "0.0528",
    bq_enterprise_3_years: "0.0396",
    bq_enterprise_plus_edition: "0.11",
    bq_enterprise_plus_1_year: "0.088",
    bq_enterprise_plus_3_years: "0.066",
    bq_flat_rate_flex: "0.04",
    bq_flat_rate_monthly: "20",
    bq_flat_rate_annual: "17",
    bq_on_demand: "5",
  },
  {
    bq_region: "europe-central2",
    bq_region_name: "Warsaw (europe-central2)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.052",
    bq_enterprise_edition: "0.078",
    bq_enterprise_1_year: "0.0624",
    bq_enterprise_3_years: "0.0468",
    bq_enterprise_plus_edition: "0.13",
    bq_enterprise_plus_1_year: "0.104",
    bq_enterprise_plus_3_years: "0.078",
    bq_flat_rate_flex: "0.052",
    bq_flat_rate_monthly: "26",
    bq_flat_rate_annual: "22.1",
    bq_on_demand: "6.5",
  },
  {
    bq_region: "europe-north1",
    bq_region_name: "Finland (europe-north1)",
    active_logical_storage: "0.02",
    long_term_logical_storage: "0.01",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.044",
    bq_enterprise_edition: "0.066",
    bq_enterprise_1_year: "0.0528",
    bq_enterprise_3_years: "0.0396",
    bq_enterprise_plus_edition: "0.11",
    bq_enterprise_plus_1_year: "0.088",
    bq_enterprise_plus_3_years: "0.066",
    bq_flat_rate_flex: "0.048",
    bq_flat_rate_monthly: "24",
    bq_flat_rate_annual: "20.4",
    bq_on_demand: "6",
  },
  {
    bq_region: "europe-southwest1",
    bq_region_name: "Madrid (europe-southwest1)",
    active_logical_storage: "0.02875",
    long_term_logical_storage: "0.02",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.047",
    bq_enterprise_edition: "0.0705",
    bq_enterprise_1_year: "0.0564",
    bq_enterprise_3_years: "0.0423",
    bq_enterprise_plus_edition: "0.1175",
    bq_enterprise_plus_1_year: "0.094",
    bq_enterprise_plus_3_years: "0.0705",
    bq_flat_rate_flex: "0.05",
    bq_flat_rate_monthly: "25",
    bq_flat_rate_annual: "21.25",
    bq_on_demand: "6.25",
  },
  {
    bq_region: "europe-west1",
    bq_region_name: "Belgium (europe-west1)",
    active_logical_storage: "0.02",
    long_term_logical_storage: "0.01",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.044",
    bq_enterprise_edition: "0.066",
    bq_enterprise_1_year: "0.0528",
    bq_enterprise_3_years: "0.0396",
    bq_enterprise_plus_edition: "0.11",
    bq_enterprise_plus_1_year: "0.088",
    bq_enterprise_plus_3_years: "0.066",
    bq_flat_rate_flex: "0.048",
    bq_flat_rate_monthly: "24",
    bq_flat_rate_annual: "20.4",
    bq_on_demand: "6",
  },
  {
    bq_region: "europe-west10",
    bq_region_name: "Berlin (europe-west10)",
    active_logical_storage: "0.03542",
    long_term_logical_storage: "0.02464",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.062",
    bq_enterprise_edition: "0.093",
    bq_enterprise_1_year: "0.0744",
    bq_enterprise_3_years: "0.0558",
    bq_enterprise_plus_edition: "0.155",
    bq_enterprise_plus_1_year: "0.124",
    bq_enterprise_plus_3_years: "0.093",
    bq_flat_rate_flex: "0.0616",
    bq_flat_rate_monthly: "30.8",
    bq_flat_rate_annual: "26.18",
    bq_on_demand: "7.7",
  },
  {
    bq_region: "europe-west12",
    bq_region_name: "Turin (europe-west12)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.052",
    bq_enterprise_edition: "0.078",
    bq_enterprise_1_year: "0.0624",
    bq_enterprise_3_years: "0.0468",
    bq_enterprise_plus_edition: "0.13",
    bq_enterprise_plus_1_year: "0.104",
    bq_enterprise_plus_3_years: "0.078",
    bq_flat_rate_flex: "0.0516",
    bq_flat_rate_monthly: "25.8",
    bq_flat_rate_annual: "21.93",
    bq_on_demand: "6.45",
  },
  {
    bq_region: "europe-west2",
    bq_region_name: "London (europe-west2)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.052",
    bq_enterprise_edition: "0.078",
    bq_enterprise_1_year: "0.0624",
    bq_enterprise_3_years: "0.0468",
    bq_enterprise_plus_edition: "0.13",
    bq_enterprise_plus_1_year: "0.104",
    bq_enterprise_plus_3_years: "0.078",
    bq_flat_rate_flex: "0.05",
    bq_flat_rate_monthly: "25",
    bq_flat_rate_annual: "21.25",
    bq_on_demand: "6.25",
  },
  {
    bq_region: "europe-west3",
    bq_region_name: "Frankfurt (europe-west3)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.052",
    bq_enterprise_edition: "0.078",
    bq_enterprise_1_year: "0.0624",
    bq_enterprise_3_years: "0.0468",
    bq_enterprise_plus_edition: "0.13",
    bq_enterprise_plus_1_year: "0.104",
    bq_enterprise_plus_3_years: "0.078",
    bq_flat_rate_flex: "0.052",
    bq_flat_rate_monthly: "26",
    bq_flat_rate_annual: "22.1",
    bq_on_demand: "6.5",
  },
  {
    bq_region: "europe-west4",
    bq_region_name: "Netherlands (europe-west4)",
    active_logical_storage: "0.02",
    long_term_logical_storage: "0.01",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.044",
    bq_enterprise_edition: "0.066",
    bq_enterprise_1_year: "0.0528",
    bq_enterprise_3_years: "0.0396",
    bq_enterprise_plus_edition: "0.11",
    bq_enterprise_plus_1_year: "0.088",
    bq_enterprise_plus_3_years: "0.066",
    bq_flat_rate_flex: "0.048",
    bq_flat_rate_monthly: "24",
    bq_flat_rate_annual: "20.4",
    bq_on_demand: "6",
  },
  {
    bq_region: "europe-west5",
    bq_region_name: "Galaxy Frankfurt (europe-west5)",
    active_logical_storage: null,
    long_term_logical_storage: null,
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.048",
    bq_enterprise_edition: "0.072",
    bq_enterprise_1_year: "0.0576",
    bq_enterprise_3_years: "0.0432",
    bq_enterprise_plus_edition: "0.12",
    bq_enterprise_plus_1_year: "0.096",
    bq_enterprise_plus_3_years: "0.072",
    bq_flat_rate_flex: null,
    bq_flat_rate_monthly: null,
    bq_flat_rate_annual: null,
    bq_on_demand: null,
  },
  {
    bq_region: "europe-west6",
    bq_region_name: "Zurich (europe-west6)",
    active_logical_storage: "0.025",
    long_term_logical_storage: "0.017",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.056",
    bq_enterprise_edition: "0.084",
    bq_enterprise_1_year: "0.0672",
    bq_enterprise_3_years: "0.0504",
    bq_enterprise_plus_edition: "0.14",
    bq_enterprise_plus_1_year: "0.112",
    bq_enterprise_plus_3_years: "0.084",
    bq_flat_rate_flex: "0.056",
    bq_flat_rate_monthly: "28",
    bq_flat_rate_annual: "23.8",
    bq_on_demand: "7",
  },
  {
    bq_region: "europe-west8",
    bq_region_name: "Milan (europe-west8)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.052",
    bq_enterprise_edition: "0.078",
    bq_enterprise_1_year: "0.0624",
    bq_enterprise_3_years: "0.0468",
    bq_enterprise_plus_edition: "0.13",
    bq_enterprise_plus_1_year: "0.104",
    bq_enterprise_plus_3_years: "0.078",
    bq_flat_rate_flex: "0.05",
    bq_flat_rate_monthly: "25",
    bq_flat_rate_annual: "21.25",
    bq_on_demand: "6.25",
  },
  {
    bq_region: "europe-west9",
    bq_region_name: "Paris (europe-west9)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.052",
    bq_enterprise_edition: "0.078",
    bq_enterprise_1_year: "0.0624",
    bq_enterprise_3_years: "0.0468",
    bq_enterprise_plus_edition: "0.13",
    bq_enterprise_plus_1_year: "0.104",
    bq_enterprise_plus_3_years: "0.078",
    bq_flat_rate_flex: "0.05",
    bq_flat_rate_monthly: "25",
    bq_flat_rate_annual: "21.25",
    bq_on_demand: "6.25",
  },
  {
    bq_region: "me-central1",
    bq_region_name: "Doha (me-central1)",
    active_logical_storage: "0.02645",
    long_term_logical_storage: "0.0184",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.049",
    bq_enterprise_edition: "0.0735",
    bq_enterprise_1_year: "0.0588",
    bq_enterprise_3_years: "0.0441",
    bq_enterprise_plus_edition: "0.1225",
    bq_enterprise_plus_1_year: "0.098",
    bq_enterprise_plus_3_years: "0.0735",
    bq_flat_rate_flex: "0.0486",
    bq_flat_rate_monthly: "24.3",
    bq_flat_rate_annual: "20.655",
    bq_on_demand: "6.075",
  },
  {
    bq_region: "me-central2",
    bq_region_name: "Dammam (me-central2)",
    active_logical_storage: "0.037",
    long_term_logical_storage: "0.026",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.064",
    bq_enterprise_edition: "0.096",
    bq_enterprise_1_year: "0.0768",
    bq_enterprise_3_years: "0.0576",
    bq_enterprise_plus_edition: "0.16",
    bq_enterprise_plus_1_year: "0.128",
    bq_enterprise_plus_3_years: "0.096",
    bq_flat_rate_flex: "0.064",
    bq_flat_rate_monthly: "32",
    bq_flat_rate_annual: "27.2",
    bq_on_demand: "8",
  },
  {
    bq_region: "me-west1",
    bq_region_name: "Israel (me-west1)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.05",
    bq_enterprise_edition: "0.075",
    bq_enterprise_1_year: "0.06",
    bq_enterprise_3_years: "0.045",
    bq_enterprise_plus_edition: "0.125",
    bq_enterprise_plus_1_year: "0.1",
    bq_enterprise_plus_3_years: "0.075",
    bq_flat_rate_flex: "0.048",
    bq_flat_rate_monthly: "24",
    bq_flat_rate_annual: "20.4",
    bq_on_demand: "6",
  },
  {
    bq_region: "northamerica-northeast1",
    bq_region_name: "Montreal (northamerica-northeast1)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.046",
    bq_enterprise_edition: "0.069",
    bq_enterprise_1_year: "0.0552",
    bq_enterprise_3_years: "0.0414",
    bq_enterprise_plus_edition: "0.115",
    bq_enterprise_plus_1_year: "0.092",
    bq_enterprise_plus_3_years: "0.069",
    bq_flat_rate_flex: "0.042",
    bq_flat_rate_monthly: "21",
    bq_flat_rate_annual: "17.85",
    bq_on_demand: "5.25",
  },
  {
    bq_region: "northamerica-northeast2",
    bq_region_name: "Toronto (northamerica-northeast2)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.044",
    bq_enterprise_edition: "0.066",
    bq_enterprise_1_year: "0.0528",
    bq_enterprise_3_years: "0.0396",
    bq_enterprise_plus_edition: "0.11",
    bq_enterprise_plus_1_year: "0.088",
    bq_enterprise_plus_3_years: "0.066",
    bq_flat_rate_flex: "0.042",
    bq_flat_rate_monthly: "21",
    bq_flat_rate_annual: "17.85",
    bq_on_demand: "5.25",
  },
  {
    bq_region: "southamerica-east1",
    bq_region_name: "Sao Paulo (southamerica-east1)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.062",
    bq_enterprise_edition: "0.093",
    bq_enterprise_1_year: "0.0744",
    bq_enterprise_3_years: "0.0558",
    bq_enterprise_plus_edition: "0.155",
    bq_enterprise_plus_1_year: "0.124",
    bq_enterprise_plus_3_years: "0.093",
    bq_flat_rate_flex: "0.072",
    bq_flat_rate_monthly: "36",
    bq_flat_rate_annual: "30.6",
    bq_on_demand: "9",
  },
  {
    bq_region: "southamerica-west1",
    bq_region_name: "Santiago (southamerica-west1)",
    active_logical_storage: "0.03289",
    long_term_logical_storage: "0.02288",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.057",
    bq_enterprise_edition: "0.0855",
    bq_enterprise_1_year: "0.0684",
    bq_enterprise_3_years: "0.0513",
    bq_enterprise_plus_edition: "0.1425",
    bq_enterprise_plus_1_year: "0.114",
    bq_enterprise_plus_3_years: "0.0855",
    bq_flat_rate_flex: "0.0572",
    bq_flat_rate_monthly: "28.6",
    bq_flat_rate_annual: "24.31",
    bq_on_demand: "7.15",
  },
  {
    bq_region: "us",
    bq_region_name: "US (multi-region)",
    active_logical_storage: "0.02",
    long_term_logical_storage: "0.01",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.04",
    bq_enterprise_edition: "0.06",
    bq_enterprise_1_year: "0.048",
    bq_enterprise_3_years: "0.036",
    bq_enterprise_plus_edition: "0.1",
    bq_enterprise_plus_1_year: "0.08",
    bq_enterprise_plus_3_years: "0.06",
    bq_flat_rate_flex: "0.04",
    bq_flat_rate_monthly: "20",
    bq_flat_rate_annual: "17",
    bq_on_demand: "5",
  },
  {
    bq_region: "us-central1",
    bq_region_name: "Iowa (us-central1)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.04",
    bq_enterprise_edition: "0.06",
    bq_enterprise_1_year: "0.048",
    bq_enterprise_3_years: "0.036",
    bq_enterprise_plus_edition: "0.1",
    bq_enterprise_plus_1_year: "0.08",
    bq_enterprise_plus_3_years: "0.06",
    bq_flat_rate_flex: "0.04",
    bq_flat_rate_monthly: "20",
    bq_flat_rate_annual: "17",
    bq_on_demand: "5",
  },
  {
    bq_region: "us-central2",
    bq_region_name: "Oklahoma (us-central2)",
    active_logical_storage: null,
    long_term_logical_storage: null,
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.04",
    bq_enterprise_edition: "0.06",
    bq_enterprise_1_year: "0.048",
    bq_enterprise_3_years: "0.036",
    bq_enterprise_plus_edition: "0.1",
    bq_enterprise_plus_1_year: "0.08",
    bq_enterprise_plus_3_years: "0.06",
    bq_flat_rate_flex: null,
    bq_flat_rate_monthly: null,
    bq_flat_rate_annual: null,
    bq_on_demand: null,
  },
  {
    bq_region: "us-east1",
    bq_region_name: "South Carolina (us-east1)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.04",
    bq_enterprise_edition: "0.06",
    bq_enterprise_1_year: "0.048",
    bq_enterprise_3_years: "0.036",
    bq_enterprise_plus_edition: "0.1",
    bq_enterprise_plus_1_year: "0.08",
    bq_enterprise_plus_3_years: "0.06",
    bq_flat_rate_flex: "0.04",
    bq_flat_rate_monthly: "20",
    bq_flat_rate_annual: "17",
    bq_on_demand: "5",
  },
  {
    bq_region: "us-east4",
    bq_region_name: "Northern Virginia (us-east4)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.04",
    bq_enterprise_edition: "0.06",
    bq_enterprise_1_year: "0.048",
    bq_enterprise_3_years: "0.036",
    bq_enterprise_plus_edition: "0.1",
    bq_enterprise_plus_1_year: "0.08",
    bq_enterprise_plus_3_years: "0.06",
    bq_flat_rate_flex: "0.04",
    bq_flat_rate_monthly: "20",
    bq_flat_rate_annual: "17",
    bq_on_demand: "5",
  },
  {
    bq_region: "us-east5",
    bq_region_name: "Columbus (us-east5)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.04",
    bq_enterprise_edition: "0.06",
    bq_enterprise_1_year: "0.048",
    bq_enterprise_3_years: "0.036",
    bq_enterprise_plus_edition: "0.1",
    bq_enterprise_plus_1_year: "0.08",
    bq_enterprise_plus_3_years: "0.06",
    bq_flat_rate_flex: "0.04",
    bq_flat_rate_monthly: "20",
    bq_flat_rate_annual: "17",
    bq_on_demand: "5",
  },
  {
    bq_region: "us-east7",
    bq_region_name: "Alabama (us-east7)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.04",
    bq_enterprise_edition: "0.06",
    bq_enterprise_1_year: "0.048",
    bq_enterprise_3_years: "0.036",
    bq_enterprise_plus_edition: "0.1",
    bq_enterprise_plus_1_year: "0.08",
    bq_enterprise_plus_3_years: "0.06",
    bq_flat_rate_flex: "0.04",
    bq_flat_rate_monthly: "20",
    bq_flat_rate_annual: "17",
    bq_on_demand: "5",
  },
  {
    bq_region: "us-south1",
    bq_region_name: "Dallas (us-south1)",
    active_logical_storage: "0.0276",
    long_term_logical_storage: "0.0192",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.047",
    bq_enterprise_edition: "0.0705",
    bq_enterprise_1_year: "0.0564",
    bq_enterprise_3_years: "0.0423",
    bq_enterprise_plus_edition: "0.1175",
    bq_enterprise_plus_1_year: "0.094",
    bq_enterprise_plus_3_years: "0.0705",
    bq_flat_rate_flex: "0.048",
    bq_flat_rate_monthly: "24",
    bq_flat_rate_annual: "20.4",
    bq_on_demand: "6",
  },
  {
    bq_region: "us-west1",
    bq_region_name: "Oregon (us-west1)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.04",
    bq_enterprise_edition: "0.06",
    bq_enterprise_1_year: "0.048",
    bq_enterprise_3_years: "0.036",
    bq_enterprise_plus_edition: "0.1",
    bq_enterprise_plus_1_year: "0.08",
    bq_enterprise_plus_3_years: "0.06",
    bq_flat_rate_flex: "0.04",
    bq_flat_rate_monthly: "20",
    bq_flat_rate_annual: "17",
    bq_on_demand: "5",
  },
  {
    bq_region: "us-west2",
    bq_region_name: "Los Angeles (us-west2)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.05",
    bq_enterprise_edition: "0.075",
    bq_enterprise_1_year: "0.06",
    bq_enterprise_3_years: "0.045",
    bq_enterprise_plus_edition: "0.125",
    bq_enterprise_plus_1_year: "0.1",
    bq_enterprise_plus_3_years: "0.075",
    bq_flat_rate_flex: "0.054",
    bq_flat_rate_monthly: "27",
    bq_flat_rate_annual: "22.95",
    bq_on_demand: "6.75",
  },
  {
    bq_region: "us-west3",
    bq_region_name: "Salt Lake City (us-west3)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.05",
    bq_enterprise_edition: "0.075",
    bq_enterprise_1_year: "0.06",
    bq_enterprise_3_years: "0.045",
    bq_enterprise_plus_edition: "0.125",
    bq_enterprise_plus_1_year: "0.1",
    bq_enterprise_plus_3_years: "0.075",
    bq_flat_rate_flex: "0.054",
    bq_flat_rate_monthly: "27",
    bq_flat_rate_annual: "22.95",
    bq_on_demand: "6.75",
  },
  {
    bq_region: "us-west4",
    bq_region_name: "Las Vegas (us-west4)",
    active_logical_storage: "0.023",
    long_term_logical_storage: "0.016",
    active_physical_storage: null,
    long_term_physical_storage: null,
    bq_standard_edition: "0.04",
    bq_enterprise_edition: "0.06",
    bq_enterprise_1_year: "0.048",
    bq_enterprise_3_years: "0.036",
    bq_enterprise_plus_edition: "0.1",
    bq_enterprise_plus_1_year: "0.08",
    bq_enterprise_plus_3_years: "0.06",
    bq_flat_rate_flex: "0.04",
    bq_flat_rate_monthly: "20",
    bq_flat_rate_annual: "17",
    bq_on_demand: "5",
  },
];

module.exports = { PRICING };
